name: Playwright Tests
on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
  #  - name: Install dependencies
   #   run: npm ci
   # - name: Install Playwright Browsers
   #   run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test tests/authorized/login.spec.js
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  release:
    name: 🚀 Create GitHub Release
  needs: build-and-test
  if: always()  # Ensure the release job runs even if build-and-test fails
  runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 📥 Download Serenity Reports
        uses: actions/download-artifact@v4
        with:
          name: serenity-reports
          path: artifacts/

      - name: 🚀 Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: Serenity Report Release.${{ github.run_number }}
          body: "Automated release of Serenity reports."
          draft: false
          prerelease: false
          artifacts: "artifacts/serenity-reports.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
